ARG VLLM_ASCEND_IMAGE=quay.nju.edu.cn/ascend/vllm-ascend
ARG VLLM_ASCEND_TAG=v0.11.0rc2
FROM ${VLLM_ASCEND_IMAGE}:${VLLM_ASCEND_TAG}

ARG APP_DIR=/vllm-workspace/vllm-omni
WORKDIR ${APP_DIR}

COPY . .

# Install vllm-omni with dev dependencies
RUN pip install --no-cache-dir -e ".[dev]"

ENV VLLM_WORKER_MULTIPROC_METHOD=spawn

ENTRYPOINT []
